#!/bin/bash

set -e


width=600
height=400

cd "$(dirname "$0")"

while read -d $'\0' file
do
    thumbnail="${file}.jpg"
    if [[ ! -f "$thumbnail" ]]
    then
        ffmpeg -itsoffset -120 \
               -i "$file" \
               -vframes 1 \
               -vf "
                   scale=iw*min($width/iw\,$height/ih):ih*min($width/iw\,$height/ih),
                   pad=$width:$height:($width-iw)/2:($height-ih)/2
               " \
               "$thumbnail" < /dev/null
    fi

done < <(find -L \
              -type f \
              -regextype posix-extended \
              -regex '.*\.(mkv|mp4|avi)' \
              -print0 | sort -z)
